spring.application.name=member-service
spring.config.import=optional:classpath:application-secret.properties

server.port=8082

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_member?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul

spring.jpa.hibernate.ddl-auto=update
