spring.application.name=gateway-service
spring.config.import=optional:classpath:application-secret.properties

server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=${PRODUCT_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/products/**,/api/promotions/**

spring.cloud.gateway.server.webflux.routes[1].id=member-service
spring.cloud.gateway.server.webflux.routes[1].uri=${MEMBER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/members/**,/api/auth/**,/oauth2/**,/login/**
